const USER_SESSION_API = {
  get_auth_token: "auth/get-auth-token",
  send_otp: "auth/send-otp",
  // send_otp: 'send-otp',
  verify_otp: "auth/verify-otp",
  register: "doctors/signup",
  login: "doctors/login",
  // create_edit_profile: 'create-edit-profile',
  update_profile: "doctors/edit-profile",
  get_profile: "doctors/get-profile",
  logout: "doctors/logout",
  delete_account: "doctors/delete-account",

  reset_password: "doctors/reset-password",
  update_password: "doctors/change-password",
  // change_password: 'change-password',
  welcome_text: "welcome-text",
  version_control: "version-control",
  manage_profile_picture: "doctors/delete-profile-img",
  doctor_check_email: "doctors/check-dr-email",
  forgot_password: "doctors/forgot-password",
  speciality_education: "doctors/speciality-education",
  forgot_verification: "doctors/verify-otp",
};
const APP_SESSION_API = {
  upload_chat_media: "doctors/upload-chat-media",
  user_list: "user-list",
  create_group: "create-group",
  upcoming_appointments: "doctors/my-appointment",
  past_appointment: "doctors/past-appointment",
  doctors_biometric_status: "doctors/biometric-status",
  doctors_appointment_details: "doctors/appointment-details",
  doctors_appointment_list: "doctors/appointment-list",
  doctors_respond_appointment: "doctors/respond-appointment",
  doctors_add_available_slot: "doctors/add-available-slot",
  doctors_add_unavailable_slot: "doctors/add-unavailable-slot",
  doctors_show_available_slot: "doctors/show-available-slot",
  doctors_delete_available_slot: "doctors/delete-slot",
  doctors_delete_unavailable_slot: "doctors/delete-unavailable-slot",
  doctors_show_unavailable_slot: "doctors/show-unavailable-slot",
  doctors_stripe_connect: "doctors/customer-stripe-connection",
  doctors_help_and_support: "doctors/help-and-support",
  api_doctors_all_review: "doctors/all-review",
  medi_user_list: "doctors/medication-user-list",
  review_details: "doctors/review-detail",
  reply_review: "doctors/reply-review",
  doctors_user_medication_detail: "doctors/user-medication-detail",
  doctors_get_wallet_history: "doctors/get-wallet-history",
  doctor_update_fcm: "doctors/update-device-token",
  doctors_notification_status: "doctors/notification-status",
  doctors_notification_list: "doctors/notification-list",
  doctor_delete_notification_list: "doctors/delete-notification-list",
  doctor_add_report: "doctors/add-report",
};

export { USER_SESSION_API, APP_SESSION_API };
